### ISSUE TITLE
Arguments passed to callback functions in aspect.after is incorrect

### ISSUE THREAD

**Issue by davidLeonardi** [hufyhang/aspect-js#1]
The arguments passed to callback functions in aspect.after is undefined, instead of being the expected value.
Upon inspecting `arguments` in the callback, i can observe that the arguments array contains two elements, the first one being `undefined` and the second one being the value I expect.

**Comment by hufyhang** [comment]
@sethx Hi there, sorry for the delay. I just tested the code and didn't encounter this issue. Would you be possible to show me your code?

**Comment by hufyhang** [comment]
Since there was no further responses received. I'm now going to close this issue.
